# PCA - Full

In [1]:
import pandas as pd

## Load Data

In [2]:
DATA_DIR = '../../data/'
DATA_SIZE_DIR = '../../data/raw/full/'

In [3]:
import pandas as pd

train_data = pd.read_csv(DATA_SIZE_DIR + 'train.csv')

train_data.info()
train_data.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53188 entries, 0 to 53187
Columns: 112 entries, qty_dot_url to phishing
dtypes: float64(1), int64(111)
memory usage: 45.4 MB

,qty_dot_url,qty_hyphen_url,qty_underline_url,qty_slash_url,qty_questionmark_url,qty_equal_url,qty_at_url,qty_and_url,qty_exclamation_url,qty_space_url,...,qty_ip_resolved,qty_nameservers,qty_mx_servers,ttl_hostname,tls_ssl_certificate,qty_redirects,url_google_index,domain_google_index,url_shortened,phishing
0,8,1,1,5,0,0,0,0,0,0,...,1,4,0,11,1,0,0,0,0,1
1,2,0,0,0,0,0,0,0,0,0,...,1,1,1,21592,0,0,0,0,0,0
2,2,0,0,1,0,0,0,0,0,0,...,4,4,2,194,1,1,0,0,0,0
3,3,0,0,6,0,0,0,0,0,0,...,1,2,1,3165,0,0,0,0,0,1
4,3,0,0,0,0,0,0,0,0,0,...,1,2,5,4914,0,-1,0,0,0,0

In [4]:
valid_data = pd.read_csv(DATA_SIZE_DIR + 'valid.csv')

valid_data.info()
valid_data.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17729 entries, 0 to 17728
Columns: 112 entries, qty_dot_url to phishing
dtypes: float64(1), int64(111)
memory usage: 15.1 MB

,qty_dot_url,qty_hyphen_url,qty_underline_url,qty_slash_url,qty_questionmark_url,qty_equal_url,qty_at_url,qty_and_url,qty_exclamation_url,qty_space_url,...,qty_ip_resolved,qty_nameservers,qty_mx_servers,ttl_hostname,tls_ssl_certificate,qty_redirects,url_google_index,domain_google_index,url_shortened,phishing
0,1,0,0,3,0,0,0,0,0,0,...,1,2,1,14391,0,0,0,0,0,1
1,1,1,0,2,0,0,0,0,0,0,...,1,2,1,14383,1,1,0,0,0,1
2,2,0,0,0,0,0,0,0,0,0,...,1,3,0,1798,1,2,0,0,0,0
3,2,0,0,0,0,0,0,0,0,0,...,1,2,5,593,0,0,0,0,0,0
4,2,0,0,0,0,0,0,0,0,0,...,1,2,2,14392,1,-1,0,0,0,0

In [5]:
test_data = pd.read_csv(DATA_SIZE_DIR + 'test.csv')

test_data.info()
test_data.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17730 entries, 0 to 17729
Columns: 112 entries, qty_dot_url to phishing
dtypes: float64(1), int64(111)
memory usage: 15.2 MB

,qty_dot_url,qty_hyphen_url,qty_underline_url,qty_slash_url,qty_questionmark_url,qty_equal_url,qty_at_url,qty_and_url,qty_exclamation_url,qty_space_url,...,qty_ip_resolved,qty_nameservers,qty_mx_servers,ttl_hostname,tls_ssl_certificate,qty_redirects,url_google_index,domain_google_index,url_shortened,phishing
0,1,0,0,1,0,0,0,0,0,0,...,1,4,0,292,1,1,0,0,1,1
1,2,0,0,0,0,0,0,0,0,0,...,1,2,1,598,0,0,0,0,0,0
2,2,0,0,5,0,0,0,0,0,0,...,1,2,5,10792,1,0,0,0,0,1
3,2,0,0,0,0,0,0,0,0,0,...,1,2,1,21599,0,0,0,0,0,0
4,2,0,0,0,0,0,0,0,0,0,...,1,2,1,1198,0,0,0,0,0,0

## Get feature data

In [6]:
TARGET_COL_NAME = 'phishing'

In [7]:
X_train = train_data.drop(TARGET_COL_NAME, axis=1)
X_valid = valid_data.drop(TARGET_COL_NAME, axis=1)
X_test = test_data.drop(TARGET_COL_NAME, axis=1)

## Dimensionality reduction - PCA

In [8]:
from sklearn.decomposition import PCA

num_components = 0.99

pca = PCA(n_components=num_components, svd_solver='full')

In [9]:
X_train_pca = pd.DataFrame(pca.fit_transform(X_train))

X_train_pca.info()
X_train_pca.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53188 entries, 0 to 53187
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       53188 non-null  float64
 1   1       53188 non-null  float64
dtypes: float64(2)
memory usage: 831.2 KB

              0             1
0   4830.801961  -6330.299302
1 -14467.013254  15757.274788
2 -31170.196073  -5210.997729
3 -26445.554390  -2455.233558
4 -14570.950655  -1111.213349

In [10]:
X_valid_pca = pd.DataFrame(pca.transform(X_valid))

X_valid_pca.info()
X_valid_pca.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17729 entries, 0 to 17728
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       17729 non-null  float64
 1   1       17729 non-null  float64
dtypes: float64(2)
memory usage: 277.1 KB

              0            1
0   5415.186815  8258.201001
1  15674.611993  7932.382171
2 -17073.070175 -4104.591626
3 -31149.738016 -5158.790821
4 -18442.641510  8602.424313

In [11]:
X_test_pca = pd.DataFrame(pca.transform(X_test))

X_test_pca.info()
X_test_pca.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17730 entries, 0 to 17729
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       17730 non-null  float64
 1   1       17730 non-null  float64
dtypes: float64(2)
memory usage: 277.2 KB

              0             1
0 -15993.023610  -5551.742121
1  30811.232069  -6153.150604
2  -4491.923092   4680.105707
3 -12066.791484  15720.718702
4   5497.471347  -5012.329154

## Save reduced datasets

In [12]:
pd.concat([X_train_pca, train_data[TARGET_COL_NAME]], axis=1).to_csv(DATA_DIR + 'reduced/full/PCA_train.csv', index=False)
pd.concat([X_valid_pca, valid_data[TARGET_COL_NAME]], axis=1).to_csv(DATA_DIR + 'reduced/full/PCA_valid.csv', index=False)
pd.concat([X_test_pca, test_data[TARGET_COL_NAME]], axis=1).to_csv(DATA_DIR + 'reduced/full/PCA_test.csv', index=False)