# PCA - Small

In [1]:
import pandas as pd

## Load Data

In [2]:
DATA_DIR = '../../data/'
DATA_SIZE_DIR = '../../data/raw/small/'

In [3]:
import pandas as pd

train_data = pd.read_csv(DATA_SIZE_DIR + 'train.csv')

train_data.info()
train_data.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35187 entries, 0 to 35186
Columns: 112 entries, qty_dot_url to phishing
dtypes: float64(1), int64(111)
memory usage: 30.1 MB

,qty_dot_url,qty_hyphen_url,qty_underline_url,qty_slash_url,qty_questionmark_url,qty_equal_url,qty_at_url,qty_and_url,qty_exclamation_url,qty_space_url,...,qty_ip_resolved,qty_nameservers,qty_mx_servers,ttl_hostname,tls_ssl_certificate,qty_redirects,url_google_index,domain_google_index,url_shortened,phishing
0,1,1,2,2,0,2,0,1,0,0,...,1,3,7,596,1,0,0,0,0,1
1,2,1,1,1,0,1,0,0,0,0,...,1,4,5,298,1,0,0,0,0,1
2,2,1,0,3,0,0,0,0,0,0,...,1,2,0,299,0,1,0,0,0,1
3,4,1,0,5,0,0,0,0,0,0,...,1,2,1,13785,1,0,0,0,0,1
4,1,0,0,0,0,0,0,0,0,0,...,2,2,1,299,1,1,0,0,0,0

In [4]:
valid_data = pd.read_csv(DATA_SIZE_DIR + 'valid.csv')

valid_data.info()
valid_data.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11729 entries, 0 to 11728
Columns: 112 entries, qty_dot_url to phishing
dtypes: float64(1), int64(111)
memory usage: 10.0 MB

,qty_dot_url,qty_hyphen_url,qty_underline_url,qty_slash_url,qty_questionmark_url,qty_equal_url,qty_at_url,qty_and_url,qty_exclamation_url,qty_space_url,...,qty_ip_resolved,qty_nameservers,qty_mx_servers,ttl_hostname,tls_ssl_certificate,qty_redirects,url_google_index,domain_google_index,url_shortened,phishing
0,24,0,5,2,0,7,0,6,0,0,...,2,2,0,292,1,0,0,0,0,1
1,3,0,0,1,0,0,0,0,0,0,...,1,4,0,226,0,1,0,0,0,0
2,1,0,0,1,0,0,0,0,0,0,...,1,3,5,3074,1,1,0,0,0,0
3,4,0,0,1,0,0,0,0,0,0,...,1,2,1,12085,0,0,0,0,0,1
4,2,0,0,1,0,0,0,0,0,0,...,1,3,1,3598,0,0,0,0,0,0

In [5]:
test_data = pd.read_csv(DATA_SIZE_DIR + 'test.csv')

test_data.info()
test_data.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11729 entries, 0 to 11728
Columns: 112 entries, qty_dot_url to phishing
dtypes: float64(1), int64(111)
memory usage: 10.0 MB

,qty_dot_url,qty_hyphen_url,qty_underline_url,qty_slash_url,qty_questionmark_url,qty_equal_url,qty_at_url,qty_and_url,qty_exclamation_url,qty_space_url,...,qty_ip_resolved,qty_nameservers,qty_mx_servers,ttl_hostname,tls_ssl_certificate,qty_redirects,url_google_index,domain_google_index,url_shortened,phishing
0,1,0,0,3,0,0,0,0,0,0,...,1,2,1,3591,1,1,0,0,0,1
1,1,0,0,2,0,0,0,0,0,0,...,-1,4,0,-1,0,-1,0,0,0,1
2,2,0,0,0,0,0,0,0,0,0,...,1,2,1,1947,1,0,0,0,0,0
3,3,1,0,7,0,1,1,0,0,0,...,1,2,1,21568,0,0,0,0,0,1
4,1,0,0,0,0,0,0,0,0,0,...,1,2,1,7192,0,1,0,0,0,0

## Get feature data

In [6]:
TARGET_COL_NAME = 'phishing'

In [7]:
X_train = train_data.drop(TARGET_COL_NAME, axis=1)
X_valid = valid_data.drop(TARGET_COL_NAME, axis=1)
X_test = test_data.drop(TARGET_COL_NAME, axis=1)

## Dimensionality reduction - PCA

In [8]:
from sklearn.decomposition import PCA

num_components = 0.99

pca = PCA(n_components=num_components, svd_solver='full')

In [9]:
X_train_pca = pd.DataFrame(pca.fit_transform(X_train))

X_train_pca.info()
X_train_pca.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35187 entries, 0 to 35186
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       35187 non-null  float64
 1   1       35187 non-null  float64
dtypes: float64(2)
memory usage: 549.9 KB

               0            1
0  228987.058114 -7577.447893
1  -18079.501237 -4591.866489
2   -7855.407037 -4726.854052
3  229855.757883  5730.655682
4  -19920.590656 -4432.011638

In [10]:
X_valid_pca = pd.DataFrame(pca.transform(X_valid))

X_valid_pca.info()
X_valid_pca.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11729 entries, 0 to 11728
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       11729 non-null  float64
 1   1       11729 non-null  float64
dtypes: float64(2)
memory usage: 183.4 KB

              0            1
0 -19913.487308 -4573.678818
1 -18080.461643 -4663.846316
2 -19152.980778 -1755.291659
3  13510.492490  6797.767366
4  -4298.720730 -1475.949864

In [11]:
X_test_pca = pd.DataFrame(pca.transform(X_test))

X_test_pca.info()
X_test_pca.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11729 entries, 0 to 11728
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       11729 non-null  float64
 1   1       11729 non-null  float64
dtypes: float64(2)
memory usage: 183.4 KB

              0             1
0  18815.156711  -1661.175732
1 -33252.125551  -4689.002127
2 -14168.852892  -2852.311369
3 -16619.548133  16682.891987
4  21832.273241   1944.771778

## Save reduced datasets

In [12]:
pd.concat([X_train_pca, train_data[TARGET_COL_NAME]], axis=1).to_csv(DATA_DIR + 'reduced/small/PCA_train.csv', index=False)
pd.concat([X_valid_pca, valid_data[TARGET_COL_NAME]], axis=1).to_csv(DATA_DIR + 'reduced/small/PCA_valid.csv', index=False)
pd.concat([X_test_pca, test_data[TARGET_COL_NAME]], axis=1).to_csv(DATA_DIR + 'reduced/small/PCA_test.csv', index=False)